import { test, expect } from '@playwright/test';
test.setTimeout(120000);

test('test', async ({ page }) => {
  await page.goto('https://individualinsurance.healthpartners.com/hp/shopping/anonymous.html#welcome');
  await page.waitForLoadState('networkidle');
  await page.getByRole('link', { name: 'Get started' }).click();
  await page.waitForLoadState('networkidle');
  await page.getByRole('link', { name: 'Skip & Shop Plans' }).click();
  await page.waitForLoadState('networkidle');
  await page.locator('#zipCode29').click();
  await page.locator('#zipCode29').fill('55413');
  await page.locator('#firstName22').click();
  await page.locator('#firstName22').fill('Hans')
  await page.locator('#lastName23').click();
  await page.locator('#lastName23').fill('Ellis');
  await page.locator('#birthDate24').click();
  await page.locator('#birthDate24').fill('12/12/2000');
  await page.locator('#gender26').selectOption('M');
  await page.locator('#isSmoker27').click();
  await page.locator('#isSmoker27').selectOption('n');
  await page.getByRole('link', { name: 'Add Dependent' }).click();
  await page.locator('#firstName38').click();
  await page.locator('#firstName38').fill('Chris');
  await page.locator('#lastName39').click();
  await page.locator('#lastName39').fill('coenen');
  await page.locator('#birthDate40').click();
  await page.locator('#birthDate40').fill('12/12/2020');
  await page.locator('#memberRelationship41').selectOption('CHILD');
  await page.locator('#gender42').selectOption('M');
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.waitForLoadState('networkidle');
  await page.getByRole('link', { name: 'Browse all plans' }).click();
  await page.waitForLoadState('networkidle');
  await page.getByRole('link', { name: 'Add to cart' }).first().click();
  await page.waitForLoadState('networkidle');
  await page.getByRole('link', { name: 'View Cart & Enroll' }).click();
  await page.waitForLoadState('networkidle');
  await page.getByRole('link', { name: 'Enroll Now' }).click();
  await page.waitForLoadState('networkidle');
  await page.goto('https://individualinsurance.healthpartners.com/hp/application/PriorToApplying.action#1', { waitUntil: 'load', timeout: 30000 });
  await page.goto('https://individualinsurance.healthpartners.com/hp/application/PriorToApplying.action#2');
  await page.goto('https://individualinsurance.healthpartners.com/hp/application/PriorToApplying.action#3');
  await page.goto('https://individualinsurance.healthpartners.com/hp/application/PriorToApplying.action#4');
  await page.getByText('*First name MI *Last name').click();
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_userProfile_user_emailAddress').click();
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_userProfile_user_emailAddress').fill('abc@gmail.com');
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_registrationInfo_userId').click();
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_registrationInfo_userId').fill('reddy123');
  await page.getByRole('link', { name: 'Check Availability' }).click();
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_registrationInfo_password').click();
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_registrationInfo_password').fill('Password@1221');
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_registrationInfo_confirmPassword').click();
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_registrationInfo_confirmPassword').fill('Password@1221');
  await page.locator('div').filter({ hasText: 'Create your account To enroll' }).nth(2).click();
  await page.getByLabel('*\n                Security question').selectOption('What was your childhood nickname?');
  await page.getByLabel('*\n                Answer').click();
  await page.getByLabel('*\n                Answer').fill('reddy');
  await page.locator('div').filter({ hasText: 'Create your account To enroll' }).nth(2).click();
  await page.locator('.sectionContents > .leftLabels > div > .radioFields > div:nth-child(2)').click();
  await page.getByLabel('No').check();
  await page.getByRole('link', { name: 'Continue ' }).click();
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_registrationInfo_password').click();
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_registrationInfo_password').fill('Password1221');
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_registrationInfo_password').press('Tab');
  await page.locator('#priorToApplyingForm_priorToApplyingInfo_registrationInfo_confirmPassword').fill('Password1221');
  await page.locator('div').filter({ hasText: 'Create your account To enroll' }).nth(2).click();
  await page.goto('https://individualinsurance.healthpartners.com/hp/applicationservice/Application.action?appResponseCode=db569f18-9069-4cfc-90e5-bf129b7a0977');
  await page.goto('https://individualinsurance.healthpartners.com/hp/applicationservice/Application.action?appResponseCode=db569f18-9069-4cfc-90e5-bf129b7a0977#NOBACK1');
  await page.goto('https://individualinsurance.healthpartners.com/hp/applicationservice/Application.action?appResponseCode=db569f18-9069-4cfc-90e5-bf129b7a0977#NOBACK2');
  await page.goto('https://individualinsurance.healthpartners.com/hp/applicationservice/Application.action?appResponseCode=db569f18-9069-4cfc-90e5-bf129b7a0977#NOBACK1');
  await page.goto('https://individualinsurance.healthpartners.com/hp/applicationservice/Application.action?appResponseCode=db569f18-9069-4cfc-90e5-bf129b7a0977#NOBACK2');
  await page.goto('https://individualinsurance.healthpartners.com/hp/applicationservice/Application.action?appResponseCode=db569f18-9069-4cfc-90e5-bf129b7a0977#PAGEC2A9DD39F777FCCCF807');
  await page.getByRole('link', { name: 'Start enrollment ' }).click();
  await page.locator('input[name="Application\\.Applicant\\.Address_1"]').click();
  await page.locator('input[name="Application\\.Applicant\\.Address_1"]').fill('330');
  await page.locator('input[name="Application\\.Applicant\\.Address_1"]').press('Tab');
  await page.locator('input[name="Application\\.Applicant\\.Address_2"]').fill('sdbdsabdja');
  await page.locator('input[name="Application\\.Applicant\\.Address_2"]').press('Tab');
  await page.locator('input[name="Application\\.Applicant\\.City"]').click();
  await page.locator('input[name="Application\\.Applicant\\.City"]').fill('minneapolis');
  await page.locator('input[name="Application\\.Applicant\\.Home_Phone"]').click();
  await page.getByRole('textbox', { name: '###-##-####' }).click();
  await page.getByRole('link', { name: 'Continue ' }).click();
  await page.goto('https://individualinsurance.healthpartners.com/hp/applicationservice/Application.action?appResponseCode=db569f18-9069-4cfc-90e5-bf129b7a0977#PAGE36C2D0AC7G95A4E40239');
});